# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import projeto_pb2 as projeto__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.set = channel.unary_unary(
                '/projeto.Greeter/set',
                request_serializer=projeto__pb2.ChaveValor.SerializeToString,
                response_deserializer=projeto__pb2.MessageReply.FromString,
                )
        self.get = channel.unary_unary(
                '/projeto.Greeter/get',
                request_serializer=projeto__pb2.ChaveValor.SerializeToString,
                response_deserializer=projeto__pb2.MessageReply.FromString,
                )
        self.delete = channel.unary_unary(
                '/projeto.Greeter/delete',
                request_serializer=projeto__pb2.ChaveValor.SerializeToString,
                response_deserializer=projeto__pb2.MessageReply.FromString,
                )
        self.testandset = channel.unary_unary(
                '/projeto.Greeter/testandset',
                request_serializer=projeto__pb2.ChaveValor.SerializeToString,
                response_deserializer=projeto__pb2.MessageReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def set(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def testandset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'set': grpc.unary_unary_rpc_method_handler(
                    servicer.set,
                    request_deserializer=projeto__pb2.ChaveValor.FromString,
                    response_serializer=projeto__pb2.MessageReply.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=projeto__pb2.ChaveValor.FromString,
                    response_serializer=projeto__pb2.MessageReply.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=projeto__pb2.ChaveValor.FromString,
                    response_serializer=projeto__pb2.MessageReply.SerializeToString,
            ),
            'testandset': grpc.unary_unary_rpc_method_handler(
                    servicer.testandset,
                    request_deserializer=projeto__pb2.ChaveValor.FromString,
                    response_serializer=projeto__pb2.MessageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'projeto.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def set(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projeto.Greeter/set',
            projeto__pb2.ChaveValor.SerializeToString,
            projeto__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projeto.Greeter/get',
            projeto__pb2.ChaveValor.SerializeToString,
            projeto__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projeto.Greeter/delete',
            projeto__pb2.ChaveValor.SerializeToString,
            projeto__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def testandset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/projeto.Greeter/testandset',
            projeto__pb2.ChaveValor.SerializeToString,
            projeto__pb2.MessageReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
