# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: projeto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='projeto.proto',
  package='projeto',
  syntax='proto3',
  serialized_options=b'\n\030io.grpc.examples.projetoB\014ProjetoProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rprojeto.proto\x12\x07projeto\"M\n\nChaveValor\x12\r\n\x05\x63have\x18\x01 \x01(\x01\x12\x0e\n\x06versao\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\r\n\x05\x64\x61\x64os\x18\x04 \x01(\x0c\"K\n\x0cMessageReply\x12\t\n\x01\x65\x18\x01 \x01(\t\x12\x0e\n\x06versao\x18\x02 \x01(\x03\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\r\n\x05\x64\x61\x64os\x18\x04 \x01(\x0c\x32\xa1\x02\n\x07Greeter\x12\x33\n\x03set\x12\x13.projeto.ChaveValor\x1a\x15.projeto.MessageReply\"\x00\x12\x33\n\x03get\x12\x13.projeto.ChaveValor\x1a\x15.projeto.MessageReply\"\x00\x12\x36\n\x06\x64\x65lete\x12\x13.projeto.ChaveValor\x1a\x15.projeto.MessageReply\"\x00\x12\x38\n\x08\x64\x65l_vers\x12\x13.projeto.ChaveValor\x1a\x15.projeto.MessageReply\"\x00\x12:\n\ntestandset\x12\x13.projeto.ChaveValor\x1a\x15.projeto.MessageReply\"\x00\x42\x30\n\x18io.grpc.examples.projetoB\x0cProjetoProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_CHAVEVALOR = _descriptor.Descriptor(
  name='ChaveValor',
  full_name='projeto.ChaveValor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chave', full_name='projeto.ChaveValor.chave', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versao', full_name='projeto.ChaveValor.versao', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='projeto.ChaveValor.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dados', full_name='projeto.ChaveValor.dados', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=103,
)


_MESSAGEREPLY = _descriptor.Descriptor(
  name='MessageReply',
  full_name='projeto.MessageReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='e', full_name='projeto.MessageReply.e', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='versao', full_name='projeto.MessageReply.versao', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='projeto.MessageReply.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dados', full_name='projeto.MessageReply.dados', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=180,
)

DESCRIPTOR.message_types_by_name['ChaveValor'] = _CHAVEVALOR
DESCRIPTOR.message_types_by_name['MessageReply'] = _MESSAGEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChaveValor = _reflection.GeneratedProtocolMessageType('ChaveValor', (_message.Message,), {
  'DESCRIPTOR' : _CHAVEVALOR,
  '__module__' : 'projeto_pb2'
  # @@protoc_insertion_point(class_scope:projeto.ChaveValor)
  })
_sym_db.RegisterMessage(ChaveValor)

MessageReply = _reflection.GeneratedProtocolMessageType('MessageReply', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEREPLY,
  '__module__' : 'projeto_pb2'
  # @@protoc_insertion_point(class_scope:projeto.MessageReply)
  })
_sym_db.RegisterMessage(MessageReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='projeto.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=183,
  serialized_end=472,
  methods=[
  _descriptor.MethodDescriptor(
    name='set',
    full_name='projeto.Greeter.set',
    index=0,
    containing_service=None,
    input_type=_CHAVEVALOR,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='projeto.Greeter.get',
    index=1,
    containing_service=None,
    input_type=_CHAVEVALOR,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='projeto.Greeter.delete',
    index=2,
    containing_service=None,
    input_type=_CHAVEVALOR,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='del_vers',
    full_name='projeto.Greeter.del_vers',
    index=3,
    containing_service=None,
    input_type=_CHAVEVALOR,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='testandset',
    full_name='projeto.Greeter.testandset',
    index=4,
    containing_service=None,
    input_type=_CHAVEVALOR,
    output_type=_MESSAGEREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
